### ISSUE TITLE
求助：都配置完之后运行乱码

### ISSUE THREAD

**Issue by Pinnd** [iGuan7u/Acetolog#7]
你好，非常喜欢你的主题，但是刚才配置完之后发现打开只显示乱码。

hexo自带的landscape主题正常。

环境：
Mac 10.15.3
hexo: 4.2.0
hexo-cli: 3.1.0
os: Darwin 19.3.0 darwin x64
node: 13.9.0
v8: 7.9.317.25-node.28
uv: 1.34.2
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 79
nghttp2: 1.40.0
napi: 5
llhttp: 2.0.4
openssl: 1.1.1d
cldr: 36.0
icu: 65.1
tz: 2019c
unicode: 12.1

<img width="1468" alt="截屏2020-03-04下午5 12 28" src="https://user-images.githubusercontent.com/4568711/75863746-f386ca80-5e3b-11ea-8529-fb5b97af56de.png">

**Comment by iGuan7u** [comment]
你好，感谢你选择 Acetolog。

这个现象似乎是 `hexo-renderer-pug` 插件没有生效，请检查一下。

在 hexo 工程根目录上安装依赖插件：
```
npm install hexo-renderer-pug hexo-renderer-sass hexo-wordcount hexo-auto-excerpt
```

**Comment by Pinnd** [comment]
嗯确实是，但是我反复尝试也没能成功：

hexo clean 时报错：
`User@Macbook blog % hexo clean
ERROR Plugin load failed: hexo-renderer-pug
Error: Cannot find module 'babel-runtime/core-js/object/get-own-property-symbols'
Require stack:
- /Users/Documents/blog/node_modules/babel-types/lib/index.js
- /Users/Documents/blog/node_modules/constantinople/lib/index.js
- /Users/Documents/blog/node_modules/pug-filters/lib/handle-filters.js
- /Users/Documents/blog/node_modules/pug-filters/index.js
- /Users/Documents/blog/node_modules/pug/lib/index.js
- /Users/Documents/blog/node_modules/hexo-renderer-pug/lib/pug.js
- /Users/Documents/blog/node_modules/hexo-renderer-pug/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/Documents/blog/node_modules/babel-types/lib/index.js:6:30)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/Documents/blog/node_modules/constantinople/lib/index.js:4:9)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/Documents/blog/node_modules/pug-filters/lib/handle-filters.js:4:22)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
`

我在根目录和blog目录里都分别运行了 hexo-renderer-pug --save ，结果都是如下：

```
User@MacBook ~ % npm install hexo-renderer-pug --save   
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN Totorn@1.0.0 No description
npm WARN Totorn@1.0.0 No repository field.

+ hexo-renderer-pug@1.0.0
updated 1 package and audited 3207 packages in 8.449s

8 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities


```

我也单独安装了core-js 3.6.4，用 npm install core-js@3.6.4 --save

**Comment by Pinnd** [comment]
另外 我单独运行 

`npm install hexo-renderer-pug --save`

会提示：

```
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
+ hexo-renderer-pug@1.0.0
updated 1 package and audited 3368 packages in 9.87s

7 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

但是我没找到 core-js@2.6.11 在哪里，也不知道怎么删除，刚才也单独安装了 core-js@3.6.4 ，是不是因为 core-js 的版本问题呢？需要link一下？我没找到2.6在哪，咋卸载或者link呢...

**Comment by Pinnd** [comment]
搞定了！完全不知道怎么搞定的，就全部清理了重新弄了一遍...

**Comment by iGuan7u** [comment]
呃，还是恭喜你吧。
那我关闭一下 issue 了。

Enjoy yourself.
